language: python
python:
  - "3.6"
deploy:
  provider: heroku
  api_key:
    secure: "74dd9b5f-029a-4a6e-9d64-58db96dff224"
  app:
script:
  - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
  - python manage.py migrate
  - coverage run manage.py test
