language: python
python:
- '3.6'
script:
- python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo
  'There are changes which require migrations.' && exit 1)
- python manage.py migrate
deploye:
  api_key:
    secure: YXYOy25twaSkq/K1xY9czStA4rcA+Zy745ys1vZzC4wQMLfaQx+/i6YBpDQmCcNirYRqo0QVGtT/vEmo7yFOo7ZbVgMjAdkG/LrUApFgxkw3Ii4lvGzuF1D1pAg/43yYBaQTYMl7o5ZVdq1++qPvIGWSlMIeaVp8MFnzoMbC0IA79iRnerNQiOaD95GxXUV7pt1HlM9SDbHsvuH3Wr9GH47d3QM5ihDQLZS3pk2LfZwvpEs5DA2MNLqgtokagYL0yUgDiN1J/zhW2jZgFMk6TFrnu5Y6FOgD+KXfG5D1fqKjpbRQtS/s3EGR4gtR/KvLUuU2gDhMDQcV4/kgBceujXKL0xH4+DiooDrFvuKheuWH/omdA1vcdvJO/0EHGIpDFpPm1teyG4xPKrylMJhOopw7AwO2iVTkFIke3Kg2a9jP11604KDqXQMenDVBT7ghLILC08kdJje5IUf/wkPrsszRXooiWOmiUBL1Ct0Teiom6oqfwkfyXgBkkkwaUikChoUOvsFo+mXyV1/sYEDWHWcyVr+eSY1ckhPV7yubJ0vvXCVPeuNbJlbh0dtmYRkrUmv33LtJpDAwZUHuLx2InJhRI7Hxfqv5TXlJqbteNrNNl6VwSHbnARpZadCvdxasRX1zYD4/vYmvN/o1wckHUu3AUMx6oIIScJiUyKs4lzk=
