language: python
python:
  - "3.6"
deploy:
  provider: heroku
  api_key:
    secure: "9a9e7db3-6c94-4881-8681-adbb5fbc1138"
  app: superlists
script:
  - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
  - python manage.py migrate


