language: python
python:
- '3.6'
script:
- python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo
  'There are changes which require migrations.' && exit 1)
- python manage.py migrate
deploye:
  api_key:
